const BASE_PLANS = [
  {
    key: "free",
    defaultName: "Free",
    defaultPrice: "€0",
    defaultAllowance: 25,
    defaultTagline: "Try the basics with 5 listings a month",
    defaultFeatures: () => [
      "Up to 5 listings each month",
      "4 AI images per listing",
      "Autogenerated descriptions",
    ],
  },
  {
    key: "plus",
    defaultName: "Plus",
    defaultPrice: "€10/mo",
    defaultAllowance: 450,
    defaultTagline: "50 listings with richer photo sets",
    defaultFeatures: () => [
      "50 listings per month",
      "Up to 8 AI images per listing",
      "Priority support",
    ],
  },
  {
    key: "pro",
    defaultName: "Pro",
    defaultPrice: "€40/mo",
    defaultAllowance: 4500,
    defaultTagline: "Scale to hundreds of listings",
    defaultFeatures: () => [
      "500 listings a month",
      "Up to 8 AI images per listing",
      "Fastest processing queue",
    ],
  },
];

function env(name) {
  return process.env[name];
}

function parseIntEnv(value, fallback) {
  const parsed = Number.parseInt(value ?? "", 10);
  if (Number.isFinite(parsed) && parsed >= 0) return parsed;
  return fallback;
}

function parseFeatures(raw, fallback) {
  if (typeof raw !== "string") return fallback;
  const items = raw
    .split("|")
    .map((item) => item.trim())
    .filter(Boolean);
  return items.length > 0 ? items : fallback;
}

function resolvePlan(base) {
  const prefix = `NEXT_PUBLIC_POLAR_PLAN_${base.key.toUpperCase()}`;
  const id = env(`${prefix}_ID`) || env(`${prefix}_PLAN_ID`) || null;
  const name = env(`${prefix}_NAME`) || base.defaultName;
  const price = env(`${prefix}_PRICE`) || base.defaultPrice;
  const tagline = env(`${prefix}_TAGLINE`) || base.defaultTagline;
  const allowance = parseIntEnv(env(`${prefix}_ALLOWANCE`), base.defaultAllowance);
  const features = parseFeatures(
    env(`${prefix}_FEATURES`),
    typeof base.defaultFeatures === "function"
      ? base.defaultFeatures(allowance)
      : base.defaultFeatures
  );

  return {
    key: base.key,
    id,
    name,
    price,
    allowance,
    tagline,
    features,
    isAvailable: Boolean(id),
  };
}

export function getSubscriptionPlans() {
  return BASE_PLANS.map(resolvePlan);
}
